# Generated by Django 5.2.7 on 2025-10-16 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('num_cl', models.AutoField(primary_key=True, serialize=False)),
                ('nom_cl', models.CharField(max_length=100)),
                ('prenom_cl', models.CharField(max_length=100)),
                ('rue_adr_cl', models.CharField(max_length=100)),
                ('ville_cl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('num_ho', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ho', models.CharField(max_length=100)),
                ('rue_adr_ho', models.CharField(max_length=100)),
                ('ville_ho', models.CharField(max_length=100)),
                ('nb_etoiles_ho', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeChambre',
            fields=[
                ('num_ty', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ty', models.CharField(max_length=100)),
                ('prix_ty', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ch', models.IntegerField()),
                ('num_ho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.hotel')),
                ('num_ty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.typechambre')),
            ],
            options={
                'unique_together': {('num_ch', 'num_ho')},
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_a', models.DateTimeField()),
                ('date_d', models.DateTimeField()),
                ('num_ch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.chambre')),
                ('num_cl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.client')),
                ('num_ho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.hotel')),
            ],
            options={
                'unique_together': {('num_cl', 'num_ho', 'num_ch', 'date_a')},
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_a', models.DateTimeField()),
                ('nb_jours', models.IntegerField()),
                ('nb_chambres', models.IntegerField()),
                ('num_cl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.client')),
                ('num_ho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.hotel')),
                ('num_ty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.typechambre')),
            ],
            options={
                'unique_together': {('num_cl', 'num_ho', 'num_ty', 'date_a')},
            },
        ),
    ]
