# Generated by Django 5.2.7 on 2025-10-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chambre',
            table='Chambre',
        ),
        migrations.AlterModelTable(
            name='client',
            table='Client',
        ),
        migrations.AlterModelTable(
            name='hotel',
            table='Hotel',
        ),
        migrations.AlterModelTable(
            name='occupation',
            table='Occupation',
        ),
        migrations.AlterModelTable(
            name='reservation',
            table='Reservation',
        ),
        migrations.AlterModelTable(
            name='typechambre',
            table='TypeChambre',
        ),
    ]
